### PR TITLE
Fix(sidebar): Fixes the sidebar of study dashboard 

### LINKED ISSUE #1029: [🐞 BUG]:Sidebar in Study Dashboard Doesn’t Appear in Mobile View
### Description 📝

When we create a study or open an existing study and then redirect to the dashboard, in desktop view, the sidebar is visible, but in mobile view, the sidebar doesn't seem to appear and leaves a blank white space

### Link 🔗

https://ruxailab-prod.web.app/signin

### Steps to Reproduce 🔄

1. Create a new study or open an existing study in a mobile viewport (≤ 960px)
2. Opening it results in a blank white space instead of a sidebar

### Screenshots 📸

https://github.com/user-attachments/assets/e3721609-29f8-49be-be96-5b2bd914727e

### Expected Behavior 🤔

The sidebar should appear instead of the white blank space

### Actual Behavior 😱

The white blank space appears in place of the sidebar

### Environment 🌍

chrome(mac os)

### Additional Information ℹ️

_No response_

### PR DESCRIPTION
**Pull request by rakshityadav1868**
fixes #1029 

https://github.com/user-attachments/assets/93a3f7c6-4e9b-45f1-8990-c92f8507a5d8

### CODE REVIEW

File: src/shared/components/Drawer.vue [hunk 1]
```diff
@@ -110,6 +110,20 @@ const go = (item) => {
   if (item.path === `/testview/${test.value.id}`) return window.open(item.path);
   router.push(item.path);
 };
+// Toggle drawer from GlobalToolbar
+const toggleDrawer = () => {
+  mini.value = !mini.value;
+};
+
+import { onMounted, onUnmounted } from 'vue';
```
Comment (sahitya-chandra) [inline src/shared/components/Drawer.vue]: Please move this to the top with other imports

**Review by sahitya-chandra — CHANGES_REQUESTED** [review]
Also address sonarqube warnings

**Comment by rakshityadav1868** [comment]
Fixed @sahitya-chandra

**Comment by sahitya-chandra** [comment]
Hey @rakshityadav1868, the sidebar behavior is not ideal on mobile. When the sidebar is open you are shrinking the width of the main page instead, it should be a sheet component, 
for reference you can view the sidebar on dashboard page.

**Comment by rakshityadav1868** [comment]
Fixed @sahitya-chandra 

https://github.com/user-attachments/assets/80da08b5-cd69-42c6-bf8a-41aa78e14d97

File: src/features/navigation/components/GlobalToolbar.vue [hunk 2]
```diff
@@ -130,7 +130,7 @@ const { t } = useI18n();
 // Computed
 const user = computed(() => store.getters.user);
 const iconSize = computed(() => smAndDown.value ? '18' : '20');
-const isDashboard = computed(() => route.path === '/admin');
+const isDashboard = computed(() => route.path === '/admin' || route.path.includes('manager'));
```
Comment (sahitya-chandra) [inline src/features/navigation/components/GlobalToolbar.vue]: What is this line change doing ??

**Review by sahitya-chandra — CHANGES_REQUESTED** [review]
also add a video of normal PC screen and medium size screen

File: src/features/navigation/components/GlobalToolbar.vue (hunk 2 above)
Comment (rakshityadav1868) [reply src/features/navigation/components/GlobalToolbar.vue]: By removing ("|| route.path.includes('manager')"), the toolbar will not treat your "study dashboard" as a dashboard page. @sahitya-chandra

**Comment by rakshityadav1868** [comment]
@sahitya-chandra, want me to change the sidebar opening for desktop view like mobile view, or is it ok?

desktop view:

https://github.com/user-attachments/assets/0075a34e-cff0-4243-b5f3-d32047246928

medium screen size view:

https://github.com/user-attachments/assets/f26c110e-8a19-43bc-b9d6-032cc3f1af80

**Comment by sahitya-chandra** [comment]
Current medium and desktop sidebar looks good, no need to change

**Comment by rakshityadav1868** [comment]
@sahitya-chandra can you approve  these changes orr anything else to change ?

**Comment by rakshityadav1868** [comment]
@sahitya-chandra I have also fixed this 
before:

https://github.com/user-attachments/assets/39a5e12e-7aef-4e65-b468-f6ed3bcf94c8

after:

https://github.com/user-attachments/assets/01afc463-fbf0-4831-a7d6-4654bcd59611

**Comment by rakshityadav1868** [comment]
Hey @sahitya-chandra , could you review the changes?

File: src/features/navigation/components/GlobalToolbar.vue
Comment (marcgc21) [inline src/features/navigation/components/GlobalToolbar.vue:1]: Not sure if it needs to be added. I mean, there is no link to user test, heuristic and accessibility. Indeed will exists other methods so I bet that it is not necessary

Comment (marcgc21) [reply src/features/navigation/components/GlobalToolbar.vue:1]: Can you explain why you added this? Maybe I'm losing something!

Comment (rakshityadav1868) [reply src/features/navigation/components/GlobalToolbar.vue:1]: Hey @marcgc21, I have fixed this issue. Now it is only using the route path as admin.
