### PR TITLE
Fixes all 34 ESLint warnings in the `src/shared/components` directory

### LINKED ISSUE #1627: style(lint): fix lint for src/shared/components folder
After run:

`npx eslint src/shared/components`

We should reduce the number of warnings to 0, right now it returns around 15 warnings, most of them related to lint or i18n problems.

### PR DESCRIPTION
**Pull request by rakshityadav1868**
Fixes #1627 
## Raw Text Warnings – Fixed Using i18n Keys

Replaced hardcoded strings with `$t()` translation keys to ensure proper internationalization support.

###  Updated Files

- **AccessibilityTestSettings.vue**
  - Replaced all hardcoded strings with `$t()` calls

- **StartScreenTest.vue**
  - `"Start Test"` → `$t('buttons.startTest')`

- **CooperatorTable.vue**
  - `"Go to session"` → `$t('cooperator.goToSession')`

---

## Unused Variables – Removed

Cleaned up unused props, imports, functions, and variables to improve code quality and remove warnings.

###  Updated Files

- **CardsManager.vue**
  - Removed unused props  
  - Added proper `defineEmits`

- **Drawer.vue**
  - Removed unused props

- **ManagerBanner.vue**
  - Removed unused props

- **TextBox.vue**
  - Removed unused `getHtml()` function

- **TextareaForm.vue**
  - Removed unused props

- **ButtonSend.vue**
  - Removed unused props

- **RadarChart.vue**
  - Removed unused `getChartInstance()` function

- **SelectionPieChart.vue**
  - Removed unused `ref` import

- **AcceptInvitationDialog.vue**
  - Removed unused `emit` variable assignment

- **LeaveAlert.vue**
  - Removed unused `useI18n` import

- **TemplateInfoDialog.vue**
  - Removed unused `useI18n` import  
  - Removed unused `error` variables in `catch` blocks

---

### Buttons
- `buttons.saveChanges`
- `buttons.createTemplate`
- `buttons.deleteTest`
- `buttons.deleteForever`
- `buttons.startTest`

###  Test Settings
- `testSettings.*` (all required keys added)

###  Dialogs
- `dialogs.confirmDeletion`
- `dialogs.actionCannotBeUndone`
- `dialogs.allAssociatedDataLost`

### Cooperator
- `cooperator.goToSession`

---

### BEFORE(34 WARNINGS):
Screenshot 2026-02-06 at 5 37 38 PM

### AFTER (NO WARNINGS):
Screenshot 2026-02-06 at 5 38 09 PM

### CODE REVIEW

**Review by KarinePistili — DISMISSED** [review]
When changing things related to i18n you need to add strings to all language files not only english. This is why i18n github action fails. Please adjust to have the string in all files.

You can view missing strings locally using `node i18n-diff-guard.js` script.

Image

if you add this log to the script you can see exactly which keys are missing:

Image

**Comment by rakshityadav1868** [comment]
sure @KarinePistili fixing it!!

**Comment by rakshityadav1868** [comment]
Fixed added all missing keys in every language @KarinePistili .
Screenshot 2026-02-07 at 2 42 17 AM

will keep this in mind for future contributions. thanks!!!

File: src/shared/components/dialogs/TemplateInfoDialog.vue [hunk 1]
```diff
@@ -233,8 +232,8 @@ const deleteTemplate = async () => {
   try {
     await store.dispatch('deleteTemplate', props.template.id)
     reset()
-  } catch (error) {
-    console.error('Error deleting template:', error)
+  } catch {
+    // Handle error silently or with a user-friendly message
```
Comment (jvJUCA) [inline src/shared/components/dialogs/TemplateInfoDialog.vue]:
```suggestion
  } catch (e) {
  store.commit('SET_TOAST', {
    type: 'error',
    message: 'Failed to delete template. Please try again.',
  })
}
```

**Review by jvJUCA — CHANGES_REQUESTED** [review]

**Review by jvJUCA — APPROVED** [review]
LGTM, thanks for the contribution, your changes will be added on develop!
